### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by summer1030** [xiadingZ/video-caption-pytorch#28]

**Comment by summer1030** [comment]
I cannot get good performance on msr-vtt dataset. So i want to know the Bleu_4 you got on this dataset (vgg16 features without c3d features). I have tried different learning rate, dim_hidden, optimizer.... however, not i only get 31.13% . Thank you .

**Comment by GauravKrRoy** [comment]
Hi @summer1030 I got  ValueError: not enough values to unpack (expected 3, got 2) while running train.py.
Details are:

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main(opt)
  File "train.py", line 120, in main
    train(dataloader, model, crit, optimizer, exp_lr_scheduler, opt, rl_crit)
  File "train.py", line 40, in train
    seq_probs, _ = model(fc_feats, labels, 'train')
  File "/home/pg2018/cse/18071003/.conda/envs/env_name/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pg2018/cse/18071003/video-captioning/models/S2VTModel.py", line 34, in forward
    batch_size, n_frames, _ = vid_feats.shape
ValueError: not enough values to unpack (expected 3, got 2)
(env_name) [18071003@master video-captioning]$ ValueError: n

**Comment by piperino11** [comment]
Msr vtt dataset have 10000 videos and 20 captions for each video but in this implementation only a video-caption pair for each example in train phase is considered. Therefore in total <= 10000 example for train.
someone has seen the same thing????
has anyone changed the code?

**Comment by Sciroccogti** [comment]
Our result is even worse...Bleu_4 is only 18%.

**Comment by 150104010139** [comment]
Hi @summer1030 I got ValueError: 

Traceback (most recent call last):
  File "prepro_vocab.py", line 85, in <module>
    main(params)
  File "prepro_vocab.py", line 43, in main
    videos = json.load(open(params['input_json'], 'r'))['sentences']
  File "/home/usr2/anaconda2/envs/wcx/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/usr2/anaconda2/envs/wcx/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/usr2/anaconda2/envs/wcx/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/usr2/anaconda2/envs/wcx/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 20 (char 296)

**Comment by baiyunfan123** [comment]
when i run:python train.py --gpu 0 --epochs 3001 --batch_size 300 --checkpoint_path data/save --feats_dir data/feats/resnet152 --model S2VTAttModel --dim_vid 4096
it will error：
RuntimeError： size mismatch， m1： [12000 x 2048]， m2： [4096 x 512] at C：/w/1/s/tmp_conda_3.7_055457/conda/conda-bld/pytorch_1565416617654/work/atenc\THC/generic/THCTensorMathBlas.cu：
273  
How do you solve this problem?
