### ISSUE TITLE
While running train.py got ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by GauravKrRoy** [xiadingZ/video-caption-pytorch#30]
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main(opt)
  File "train.py", line 120, in main
    train(dataloader, model, crit, optimizer, exp_lr_scheduler, opt, rl_crit)
  File "train.py", line 40, in train
    seq_probs, _ = model(fc_feats, labels, 'train')
  File "/home/pg2018/cse/18071003/.conda/envs/env_name/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/pg2018/cse/18071003/video-captioning/models/S2VTModel.py", line 34, in forward
    batch_size, n_frames, _ = vid_feats.shape
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by GauravKrRoy** [comment]
@Blues5 @Sundrops @xiadingZ  please help me to overome this error. Thank you
