### ISSUE TITLE
hi, there. I forked coco-caption and fixed the bug of meteor when using python3.

### ISSUE THREAD

**Issue by XgDuan** [xiadingZ/video-caption-pytorch#6]
here is the fixed version of coco-caption: https://github.com/XgDuan/coco-caption

**Comment by xiadingZ** [comment]
Thanks you very much, meteor works. but spice doesn't work, I hope can add this metric too. 
My python version is 3.6
```
Traceback (most recent call last):
  File "eval.py", line 117, in <module>
    main(opt)
  File "eval.py", line 92, in main
    test(model, crit, dataset, dataset.get_vocab(), opt)
  File "eval.py", line 58, in test
    valid_score = scorer.score(gts, samples, samples.keys())
  File "/home/xiading/code/video-caption/misc/cocoeval.py", line 89, in score
    score, scores = scorer.compute_score(gts, res)
  File "coco-caption/pycocoevalcap/spice/spice.py", line 70, in compute_score
    cwd=os.path.dirname(os.path.abspath(__file__)))
  File "/home/xiading/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/home  /xiading/code/video-caption/coco-caption/pycocoevalcap/spice/tmp/tmprj4uz_dw', '-cache', '  /home/xiading/code/video-caption/coco-caption/pycocoevalcap/spice/cache', '-out', '/home/x  iading/code/video-caption/coco-caption/pycocoevalcap/spice/tmp/tmpz90hhx6d', '-subset', '-  silent']' returned non-zero exit status 1.
```

**Comment by XgDuan** [comment]
Emmm, I will try it later..

**Comment by xiazhiwu-hub** [comment]
Is the problem fixed ?
